name: capsule_note
description: A minimal E-ink capsule note app with i18n and AdMob monetization.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  uuid: ^4.6.0
  record: ^5.1.2
  audioplayers: ^6.8.1
  flutter_animate: ^4.5.2
  google_mobile_ads: ^5.3.1
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  generate: true

dependency_overrides:
  record_platform_interface: 1.2.0

flutter_native_splash:
  color: "#F9F9F8"
  color_dark: "#121212"
  image: assets/icon/splash_icon.png
  image_dark: assets/icon/splash_icon.png
  android: true
  ios: true
  web: false
