import 'capsule_model.dart';

class PendingActionItem {
  final String capsuleId;
  final String capsuleTitle;
  final String actionText;
  final bool isCompleted;

  const PendingActionItem({
    required this.capsuleId,
    required this.capsuleTitle,
    required this.actionText,
    this.isCompleted = false,
  });
}

class DailyDigestModel {
  final DateTime date;
  final List<CapsuleModel> capsules;
  final int totalCapsules;
  final int processedCount;
  final int pendingCount;
  final List<String> keySummaries;
  final List<PendingActionItem> pendingActionItems;
  final Map<String, int> tagDistribution;

  const DailyDigestModel({
    required this.date,
    required this.capsules,
    required this.totalCapsules,
    required this.processedCount,
    required this.pendingCount,
    required this.keySummaries,
    required this.pendingActionItems,
    required this.tagDistribution,
  });

  double get completionRate =>
      totalCapsules == 0 ? 1.0 : (processedCount / totalCapsules).clamp(0.0, 1.0);

  factory DailyDigestModel.fromCapsules(DateTime targetDate, List<CapsuleModel> allCapsules) {
    final dayCapsules = allCapsules.where((c) {
      return c.createdAt.year == targetDate.year &&
          c.createdAt.month == targetDate.month &&
          c.createdAt.day == targetDate.day;
    }).toList()
      ..sort((a, b) => a.createdAt.compareTo(b.createdAt));

    final summaries = <String>[];
    final actions = <PendingActionItem>[];
    final tagsMap = <String, int>{};
    int processed = 0;

    for (final capsule in dayCapsules) {
      if (capsule.isProcessed) {
        processed++;
      }

      if (capsule.summary.trim().isNotEmpty) {
        summaries.add(capsule.summary.trim());
      } else if (capsule.rawTranscript.trim().isNotEmpty) {
        summaries.add(capsule.rawTranscript.trim());
      }

      for (final action in capsule.actionItems) {
        if (action.trim().isNotEmpty) {
          actions.add(
            PendingActionItem(
              capsuleId: capsule.id,
              capsuleTitle: capsule.title.isNotEmpty ? capsule.title : 'Capsule',
              actionText: action.trim(),
              isCompleted: capsule.isProcessed,
            ),
          );
        }
      }

      for (final tag in capsule.tags) {
        if (tag.trim().isNotEmpty) {
          tagsMap[tag.trim()] = (tagsMap[tag.trim()] ?? 0) + 1;
        }
      }
    }

    return DailyDigestModel(
      date: targetDate,
      capsules: dayCapsules,
      totalCapsules: dayCapsules.length,
      processedCount: processed,
      pendingCount: dayCapsules.length - processed,
      keySummaries: summaries,
      pendingActionItems: actions,
      tagDistribution: tagsMap,
    );
  }

  String toMarkdown() {
    final buffer = StringBuffer();
    final dateStr = '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';

    buffer.writeln('# 📰 Daily Inspiration Digest - $dateStr');
    buffer.writeln();
    buffer.writeln('> **Overview:** Total Capsules: $totalCapsules | Organized: $processedCount | Pending: $pendingCount | Progress: ${(completionRate * 100).toInt()}%');
    buffer.writeln();

    buffer.writeln('## 💡 Key Summaries');
    if (keySummaries.isEmpty) {
      buffer.writeln('*No summaries recorded today.*');
    } else {
      for (int i = 0; i < capsules.length; i++) {
        final c = capsules[i];
        final title = c.title.isNotEmpty ? c.title : 'Capsule #${i + 1}';
        final text = c.summary.isNotEmpty ? c.summary : c.rawTranscript;
        final timeStr = '${c.createdAt.hour.toString().padLeft(2, '0')}:${c.createdAt.minute.toString().padLeft(2, '0')}';
        buffer.writeln('- **$title** *($timeStr)*: $text');
      }
    }
    buffer.writeln();

    buffer.writeln('## 📌 Action Items To-Do');
    if (pendingActionItems.isEmpty) {
      buffer.writeln('*No action items for today.*');
    } else {
      for (final item in pendingActionItems) {
        final mark = item.isCompleted ? '[x]' : '[ ]';
        buffer.writeln('- $mark ${item.actionText} *(from ${item.capsuleTitle})*');
      }
    }
    buffer.writeln();

    if (tagDistribution.isNotEmpty) {
      buffer.writeln('## 🏷️ Topic Tags');
      final tagsStr = tagDistribution.entries
          .map((e) => '`#${e.key} (${e.value})`')
          .join(' ');
      buffer.writeln(tagsStr);
      buffer.writeln();
    }

    buffer.writeln('---');
    buffer.writeln('*Generated by Capsule Note*');
    return buffer.toString();
  }

  String toPlainText() {
    final buffer = StringBuffer();
    final dateStr = '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';

    buffer.writeln('DAILY INSPIRATION DIGEST ($dateStr)');
    buffer.writeln('========================================');
    buffer.writeln('Total Notes: $totalCapsules | Completed: $processedCount | Pending: $pendingCount');
    buffer.writeln();

    buffer.writeln('[KEY SUMMARIES]');
    if (keySummaries.isEmpty) {
      buffer.writeln('No summaries recorded.');
    } else {
      for (int i = 0; i < capsules.length; i++) {
        final c = capsules[i];
        final title = c.title.isNotEmpty ? c.title : 'Note #${i + 1}';
        final text = c.summary.isNotEmpty ? c.summary : c.rawTranscript;
        buffer.writeln('• $title: $text');
      }
    }
    buffer.writeln();

    buffer.writeln('[ACTION ITEMS]');
    if (pendingActionItems.isEmpty) {
      buffer.writeln('No pending actions.');
    } else {
      for (final item in pendingActionItems) {
        final status = item.isCompleted ? '[DONE]' : '[TODO]';
        buffer.writeln('$status ${item.actionText} (${item.capsuleTitle})');
      }
    }
    buffer.writeln();

    if (tagDistribution.isNotEmpty) {
      buffer.writeln('[TAGS]');
      buffer.writeln(tagDistribution.keys.map((k) => '#$k').join(', '));
      buffer.writeln();
    }

    return buffer.toString();
  }

  String toNotionFormat() {
    final buffer = StringBuffer();
    final dateStr = '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';

    buffer.writeln('# 📓 Daily Digest: $dateStr');
    buffer.writeln();
    buffer.writeln('> 💡 **Daily Pulse:** Today you captured $totalCapsules idea capsules. Completion Rate: ${(completionRate * 100).toInt()}%.');
    buffer.writeln();
    buffer.writeln('---');
    buffer.writeln();

    buffer.writeln('### 🧠 Key Takeaways & Summaries');
    for (final c in capsules) {
      final title = c.title.isNotEmpty ? c.title : 'Capsule';
      final text = c.summary.isNotEmpty ? c.summary : c.rawTranscript;
      final tags = c.tags.map((t) => '`$t`').join(' ');
      buffer.writeln('▶ **$title** $tags');
      buffer.writeln('  $text');
      buffer.writeln();
    }

    buffer.writeln('### ⚡ Action Items');
    for (final item in pendingActionItems) {
      final check = item.isCompleted ? '[x]' : '[ ]';
      buffer.writeln('- $check **${item.actionText}** *(Source: ${item.capsuleTitle})*');
    }
    buffer.writeln();

    buffer.writeln('---');
    final tagsStr = tagDistribution.keys.map((k) => '`#$k`').join(' ');
    buffer.writeln('🏷️ **Tags:** $tagsStr');
    return buffer.toString();
  }
}
